version: '3'
services:
   mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adfin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      - traefik_web
networks:
  traefik_web:
        external: true