version: '3'
services:
   db:
      platform: linux/x86_64
      image: mysql:5.7
      container_name: db
      restart: always
      volumes:
         - ./mysql/dbdata:/var/lib/mysql:rw
         - ./mysql/:/docker-entrypoint-initdb.d
         #- ./database/ufabet.sql:/:/docker-entrypoint-initdb.d/init.sql:ro
      ports:
         - '3306:3306'
      env_file: .env
      networks:
         - traefik_web

   pma:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
         - "8181:80"
      env_file: .env
      depends_on:
         - db
      environment:
         - PMA_HOST=db
      networks:
         - traefik_web

networks:
  traefik_web:
        external: true