version: '3.7'
services:
  bank_sv1:
    image: bank:1.0
    container_name: bank_sv1
    build:
      context: ./bank
      dockerfile: ./Dockerfile
    volumes:
      - nodemodules:/usr/local/app/node_modules
      - ./bank:/app
    environment:
      REDIS_CLUSTER: "redis-node-1:6377,redis-node-2:6378,redis-node-3:6379"
      PORT: 3333
      MONGODB: "mongodb://adfin:123456@mongodb:27017/?maxPoolSize=20&w=majority"
    networks:
      - traefik_web

      

  bank_sv2:
    image: bank:1.0
    environment:
      REDIS_CLUSTER: "redis-node-1:6377,redis-node-2:6378,redis-node-3:6379"
      PORT: 3334
      MONGODB: "mongodb://adfin:123456@mongodb:27017/?maxPoolSize=20&w=majority"

    networks:
      - traefik_web

  bank_sv3:
    image: bank:1.0
    environment:
      REDIS_CLUSTER: "redis-node-1:6377,redis-node-2:6378,redis-node-3:6379"
      PORT: 3335
      MONGODB: "mongodb://adfin:123456@mongodb:27017/?maxPoolSize=20&w=majority"

    networks:
      - traefik_web



volumes:
  nodemodules:
  
networks:
  traefik_web:
    external: true

