http:
  middlewares:
    ex-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "192.168.1.1/32"
          - "52.192.178.216"
  routers:
    whoami:
      entryPoints:
         - "websecure"
      rule: "HostRegexp(`lab.lan`, `{subdomain:[a-z]+}.lab.lan`) && !HostRegexp(`frontend.lab.lan`) && !HostRegexp(`pma.lab.lan`) && !HostRegexp(`vscode.lab.lan`)"
      service: allbackend
      #middlewares: "ex-ipwhitelist"
      tls: {}
    frontend:
      entryPoints:
        - "websecure"
      rule: "Host(`frontend.lab.lan`)"
      service: frontend
      tls: {}
    pma:
      entryPoints:
        - "websecure"
      rule: "Host(`pma.lab.lan`)"
      service: pma
      tls: {}
  
  services:
    allbackend:
      loadBalancer:
        servers:
          - url: "http://backend_sv:3333/"
          # - url: "http://bank_sv2:3334/"
          # - url: "http://bank_sv2:3335/"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend_sv:3000/"

    pma:
      loadBalancer:
        servers:
          - url: "http://pma"